---
title: "Hello World"
author: "Me"
date: "February 24, 2020"
output:
  pdf_document: default
header-includes: 
  - \usepackage{tikz}
  - \usepackage{pgfplots}
  - \usepackage{pgf,tikz,pgfplots}
  - \pgfplotsset{compat=1.15}
  - \usepackage{mathrsfs}
  - \usetikzlibrary{arrows}
  - \usetikzlibrary{patterns}
---

## TikZ picture
- Here is a TikZ picutre

\definecolor{zzffzz}{rgb}{0.6,1,0.6}
\definecolor{ffcctt}{rgb}{1,0.8,0.2}
\definecolor{yqyqdz}{rgb}{0.5019607843137255,0.5019607843137255,0.8509803921568627}
\begin{tikzpicture}
  [node distance=.8cm,
  start chain=going below,]
     \node[punktchain, join] (intro) {Introduktion};
     \node[punktchain, join] (probf)      {Problemformulering};
     \node[punktchain, join] (investeringer)      {Investeringsteori};
     \node[punktchain, join] (perfekt) {Det perfekte kapitalmarked};
     \node[punktchain, join, ] (emperi) {Emperi};
      \node (asym) [punktchain ]  {Asymmetrisk information};
      \begin{scope}[start branch=venstre,
        %We need to redefine the join-style to have the -> turn out right
        every join/.style={->, thick, shorten <=1pt}, ]
        \node[punktchain, on chain=going left, join=by {<-}]
            (risiko) {Risiko og gamble};
      \end{scope}
      \begin{scope}[start branch=hoejre,]
      \node (finans) [punktchain, on chain=going right] {Det finansielle system};
    \end{scope}
  \node[punktchain, join,] (disk) {Det imperfekte finansielle marked};
  \node[punktchain, join,] (makro) {Investeringsmæssige konsekvenser};
  \node[punktchain, join] (konk) {Konklusion};
  % Now that we have finished the main figure let us add some "after-drawings"
  %% First, let us connect (finans) with (disk). We want it to have
  %% square corners.
  \draw[|-,-|,->, thick,] (finans.south) |-+(0,-1em)-| (disk.north);
  % Now, let us add some braches. 
  %% No. 1
  \draw[tuborg] let
    \p1=(risiko.west), \p2=(finans.east) in
    ($(\x1,\y1+2.5em)$) -- ($(\x2,\y2+2.5em)$) node[above, midway]  {Teori};
  %% No. 2
  \draw[tuborg, decoration={brace}] let \p1=(disk.north), \p2=(makro.south) in
    ($(2, \y1)$) -- ($(2, \y2)$) node[tubnode] {Analyse};
  %% No. 3
  \draw[tuborg, decoration={brace}] let \p1=(perfekt.north), \p2=(emperi.south) in
    ($(2, \y1)$) -- ($(2, \y2)$) node[tubnode] {Problemfelt};
  \end{tikzpicture}